#!/bin/bash

# Script per configurare le variabili d'ambiente per i test
# Questo script aiuta a configurare .env.test con le credenziali necessarie

set -e

cd "$(dirname "$0")"

echo "🔧 Configurazione variabili d'ambiente per i test critici"
echo "============================================================"
echo ""

# Verifica se .env.test esiste
if [ -f ".env.test" ]; then
    echo "📋 File .env.test già esistente"
    read -p "Vuoi sovrascriverlo? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Operazione annullata"
        exit 0
    fi
fi

# Chiedi le credenziali all'utente
echo ""
echo "📝 Inserisci le credenziali Supabase:"
echo "   (Puoi trovarle su: https://supabase.com/dashboard → Il tuo progetto → Settings → API)"
echo ""

read -p "SUPABASE_URL [default: https://zyonwzilijgnnnmhxvbo.supabase.co]: " SUPABASE_URL
SUPABASE_URL=${SUPABASE_URL:-https://zyonwzilijgnnnmhxvbo.supabase.co}

read -p "SUPABASE_ANON_KEY [default: sb_publishable_tVK70OrNKiaVmttm2WxyXA_tMFn9bUc]: " SUPABASE_ANON_KEY
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-sb_publishable_tVK70OrNKiaVmttm2WxyXA_tMFn9bUc}

echo ""
echo "⚠️  IMPORTANTE: La SERVICE_ROLE_KEY è necessaria per i test."
echo "   Trovala su: Supabase Dashboard → Settings → API → service_role key"
echo "   ⚠️  Questa chiave ha accesso completo al database - mantienila segreta!"
echo ""
read -p "SUPABASE_SERVICE_ROLE_KEY (REQUIRED): " SUPABASE_SERVICE_ROLE_KEY

if [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
    echo "❌ ERRORE: SUPABASE_SERVICE_ROLE_KEY è obbligatoria!"
    echo "   I test non possono essere eseguiti senza questa chiave."
    exit 1
fi

# Crea il file .env.test
cat > .env.test << EOF
# Environment Variables for Critical Tests
# Generated by setup-test-env.sh
# DO NOT commit this file to git (it's in .gitignore)

# Supabase Configuration
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# Optional variables
BASE_URL=https://flixdog.com
EOF

echo ""
echo "✅ File .env.test creato con successo!"
echo ""
echo "🚀 Ora puoi eseguire i test con:"
echo "   ./run-all-critical-tests.sh"
echo "   oppure"
echo "   npm run test:critical"
echo ""

